# Generated by Django 2.1.3 on 2019-03-29 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conectores', '0002_auto_20190319_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(null=True, verbose_name='Tiempo y fecha de creación')),
                ('modified', models.DateField(null=True, verbose_name='Tiempo y fecha de modificación')),
                ('private_key', models.TextField(default='')),
                ('public_key', models.TextField(default='')),
                ('certificado', models.TextField(default='')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cert', to='conectores.Compania')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Certificados',
                'verbose_name': 'Certificado',
            },
        ),
    ]
