# Generated by Django 2.1.3 on 2019-02-02 14:39

import certificados.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conectores', '0005_auto_20190130_0910'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tiempo y fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Tiempo y fecha de modificación')),
                ('certificado', models.FileField(blank=True, null=True, upload_to=certificados.models.upload_certificate_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])], verbose_name='Certificado digital')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conectores.Compania')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
