COMUNAS = (
    ('Arica','Arica'),
    ('Camarones','Camarones'),
    ('Putre','Putre'),
    ('General Lagos','General Lagos'),
    ('Iquique','Iquique'),
    ('Alto Hospicio','Alto Hospicio'),
    ('Pozo Almonte','Pozo Almonte'),
    ('Camiña','Camiña'),
    ('Colchane','Colchane'),
    ('Huara','Huara'),
    ('Pica','Pica'),
    ('Antofagasta','Antofagasta'),
    ('Mejillones','Mejillones'),
    ('Sierra Gorda','Sierra Gorda'),
    ('Taltal','Taltal'),
    ('Calama','Calama'),
    ('Ollagüe','Ollagüe'),
    ('San Pedro de Atacama','San Pedro de Atacama'),
    ('Tocopilla','Tocopilla'),
    ('María Elena','María Elena'),
    ('Copiapó','Copiapó'),
    ('Caldera','Caldera'),
    ('Tierra Amarilla','Tierra Amarilla'),
    ('Chañaral','Chañaral'),
    ('Diego de Almagro','Diego de Almagro'),
    ('Vallenar','Vallenar'),
    ('Alto del Carmen','Alto del Carmen'),
    ('Freirina','Freirina'),
    ('Huasco','Huasco'),
    ('La Serena','La Serena'),
    ('Coquimbo','Coquimbo'),
    ('Andacollo','Andacollo'),
    ('La Higuera','La Higuera'),
    ('Paihuano','Paihuano'),
    ('Vicuña','Vicuña'),
    ('Illapel','Illapel'),
    ('Canela','Canela'),
    ('Los Vilos','Los Vilos'),
    ('Salamanca','Salamanca'),
    ('Ovalle','Ovalle'),
    ('Combarbalá','Combarbalá'),
    ('Monte Patria','Monte Patria'),
    ('Punitaqui','Punitaqui'),
    ('Río Hurtado','Río Hurtado'),
    ('Valparaíso','Valparaíso'),
    ('Casablanca','Casablanca'),
    ('Concón','Concón'),
    ('Juan Fernández','Juan Fernández'),
    ('Puchuncaví','Puchuncaví'),
    ('Quintero','Quintero'),
    ('Viña del Mar','Viña del Mar'),
    ('Isla de Pascua','Isla de Pascua'),
    ('Los Andes','Los Andes'),
    ('Calle Larga','Calle Larga'),
    ('Rinconada','Rinconada'),
    ('San Esteban','San Esteban'),
    ('La Ligua','La Ligua'),
    ('Cabildo','Cabildo'),
    ('Papudo','Papudo'),
    ('Petorca','Petorca'),
    ('Zapallar','Zapallar'),
    ('Quillota','Quillota'),
    ('La Calera','La Calera'),
    ('Hijuelas','Hijuelas'),
    ('La Cruz','La Cruz'),
    ('Nogales','Nogales'),
    ('San Antonio','San Antonio'),
    ('Algarrobo','Algarrobo'),
    ('Cartagena','Cartagena'),
    ('El Quisco','El Quisco'),
    ('El Tabo','El Tabo'),
    ('Santo Domingo','Santo Domingo'),
    ('San Felipe','San Felipe'),
    ('Catemu','Catemu'),
    ('Llaillay','Llaillay'),
    ('Panquehue','Panquehue'),
    ('Putaendo','Putaendo'),
    ('Santa María','Santa María'),
    ('Quilpué','Quilpué'),
    ('Limache','Limache'),
    ('Olmué','Olmué'),
    ('Villa Alemana','Villa Alemana'),
    ('Rancagua','Rancagua'),
    ('Codegua','Codegua'),
    ('Coinco','Coinco'),
    ('Coltauco','Coltauco'),
    ('Doñihue','Doñihue'),
    ('Graneros','Graneros'),
    ('Las Cabras','Las Cabras'),
    ('Machalí','Machalí'),
    ('Malloa','Malloa'),
    ('Mostazal','Mostazal'),
    ('Olivar','Olivar'),
    ('Peumo','Peumo'),
    ('Pichidegua','Pichidegua'),
    ('Quinta de Tilcoco','Quinta de Tilcoco'),
    ('Rengo','Rengo'),
    ('Requínoa','Requínoa'),
    ('San Vicente','San Vicente'),
    ('Pichilemu','Pichilemu'),
    ('La Estrella','La Estrella'),
    ('Litueche','Litueche'),
    ('Marchihue','Marchihue'),
    ('Navidad','Navidad'),
    ('Paredones','Paredones'),
    ('San Fernando','San Fernando'),
    ('Chépica','Chépica'),
    ('Chimbarongo','Chimbarongo'),
    ('Lolol','Lolol'),
    ('Nancagua','Nancagua'),
    ('Palmilla','Palmilla'),
    ('Peralillo','Peralillo'),
    ('Placilla','Placilla'),
    ('Pumanque','Pumanque'),
    ('Santa Cruz','Santa Cruz'),
    ('Talca','Talca'),
    ('Constitución','Constitución'),
    ('Curepto','Curepto'),
    ('Empedrado','Empedrado'),
    ('Maule','Maule'),
    ('Pelarco','Pelarco'),
    ('Pencahue','Pencahue'),
    ('Río Claro','Río Claro'),
    ('San Clemente','San Clemente'),
    ('San Rafael','San Rafael'),
    ('Cauquenes','Cauquenes'),
    ('Chanco','Chanco'),
    ('Pelluhue','Pelluhue'),
    ('Curicó','Curicó'),
    ('Hualañé','Hualañé'),
    ('Licantén','Licantén'),
    ('Molina','Molina'),
    ('Rauco','Rauco'),
    ('Romeral','Romeral'),
    ('Sagrada Familia','Sagrada Familia'),
    ('Teno','Teno'),
    ('Vichuquén','Vichuquén'),
    ('Linares','Linares'),
    ('Colbún','Colbún'),
    ('Longaví','Longaví'),
    ('Parral','Parral'),
    ('Retiro','Retiro'),
    ('San Javier','San Javier'),
    ('Villa Alegre','Villa Alegre'),
    ('Yerbas Buenas','Yerbas Buenas'),
    ('San Carlos','San Carlos'),
    ('San Fabián','San Fabián'),
    ('Coihueco','Coihueco'),
    ('Ñiquén','Ñiquén'),
    ('San Nicolás','San Nicolás'),
    ('Bulnes','Bulnes'),
    ('Chillán','Chillán'),
    ('Chillán Viejo','Chillán Viejo'),
    ('El Carmen','El Carmen'),
    ('Pemuco','Pemuco'),
    ('Pinto','Pinto'),
    ('Quillón','Quillón'),
    ('San Ignacio','San Ignacio'),
    ('Yungay','Yungay'),
    ('Quirihue','Quirihue'),
    ('Cobquecura','Cobquecura'),
    ('Coelemu','Coelemu'),
    ('Ninhue','Ninhue'),
    ('Portezuelo','Portezuelo'),
    ('Ránquil','Ránquil'),
    ('Treguaco','Treguaco'),
    ('Concepción','Concepción'),
    ('Coronel','Coronel'),
    ('Chiguayante','Chiguayante'),
    ('Florida','Florida'),
    ('Hualqui','Hualqui'),
    ('Lota','Lota'),
    ('Penco','Penco'),
    ('San Pedro de La Paz','San Pedro de La Paz'),
    ('Santa Juana','Santa Juana'),
    ('Talcahuano','Talcahuano'),
    ('Tomé','Tomé'),
    ('Hualpén','Hualpén'),
    ('Lebu','Lebu'),
    ('Arauco','Arauco'),
    ('Cañete','Cañete'),
    ('Contulmo','Contulmo'),
    ('Curanilahue','Curanilahue'),
    ('Los Álamos','Los Álamos'),
    ('Tirúa','Tirúa'),
    ('Los Ángeles','Los Ángeles'),
    ('Antuco','Antuco'),
    ('Cabrero','Cabrero'),
    ('Laja','Laja'),
    ('Mulchén','Mulchén'),
    ('Nacimiento','Nacimiento'),
    ('Negrete','Negrete'),
    ('Quilaco','Quilaco'),
    ('Quilleco','Quilleco'),
    ('San Rosendo','San Rosendo'),
    ('Santa Bárbara','Santa Bárbara'),
    ('Tucapel','Tucapel'),
    ('Yumbel','Yumbel'),
    ('Alto Biobío','Alto Biobío'),
    ('Temuco','Temuco'),
    ('Carahue','Carahue'),
    ('Cunco','Cunco'),
    ('Curarrehue','Curarrehue'),
    ('Freire','Freire'),
    ('Galvarino','Galvarino'),
    ('Gorbea','Gorbea'),
    ('Lautaro','Lautaro'),
    ('Loncoche','Loncoche'),
    ('Melipeuco','Melipeuco'),
    ('Nueva Imperial','Nueva Imperial'),
    ('Padre Las Casas','Padre Las Casas'),
    ('Perquenco','Perquenco'),
    ('Pitrufquén','Pitrufquén'),
    ('Pucón','Pucón'),
    ('Saavedra','Saavedra'),
    ('Teodoro Schmidt','Teodoro Schmidt'),
    ('Toltén','Toltén'),
    ('Vilcún','Vilcún'),
    ('Villarrica','Villarrica'),
    ('Cholchol','Cholchol'),
    ('Angol','Angol'),
    ('Collipulli','Collipulli'),
    ('Curacautín','Curacautín'),
    ('Ercilla','Ercilla'),
    ('Lonquimay','Lonquimay'),
    ('Los Sauces','Los Sauces'),
    ('Lumaco','Lumaco'),
    ('Purén','Purén'),
    ('Renaico','Renaico'),
    ('Traiguén','Traiguén'),
    ('Victoria','Victoria'),
    ('Valdivia','Valdivia'),
    ('Corral','Corral'),
    ('Lanco','Lanco'),
    ('Los Lagos','Los Lagos'),
    ('Máfil','Máfil'),
    ('Mariquina','Mariquina'),
    ('Paillaco','Paillaco'),
    ('Panguipulli','Panguipulli'),
    ('La Unión','La Unión'),
    ('Futrono','Futrono'),
    ('Lago Ranco','Lago Ranco'),
    ('Río Bueno','Río Bueno'),
    ('Puerto Montt','Puerto Montt'),
    ('Calbuco','Calbuco'),
    ('Cochamó','Cochamó'),
    ('Fresia','Fresia'),
    ('Frutillar','Frutillar'),
    ('Los Muermos','Los Muermos'),
    ('Llanquihue','Llanquihue'),
    ('Maullín','Maullín'),
    ('Puerto Varas','Puerto Varas'),
    ('Castro','Castro'),
    ('Ancud','Ancud'),
    ('Chonchi','Chonchi'),
    ('Curaco de Vélez','Curaco de Vélez'),
    ('Dalcahue','Dalcahue'),
    ('Puqueldón','Puqueldón'),
    ('Queilén','Queilén'),
    ('Quellón','Quellón'),
    ('Quemchi','Quemchi'),
    ('Quinchao','Quinchao'),
    ('Osorno','Osorno'),
    ('Puerto Octay','Puerto Octay'),
    ('Purranque','Purranque'),
    ('Puyehue','Puyehue'),
    ('Río Negro','Río Negro'),
    ('San Juan de la Costa','San Juan de la Costa'),
    ('San Pablo','San Pablo'),
    ('Chaitén','Chaitén'),
    ('Futaleufú','Futaleufú'),
    ('Hualaihué','Hualaihué'),
    ('Palena','Palena'),
    ('Coyhaique','Coyhaique'),
    ('Lago Verde','Lago Verde'),
    ('Aysén','Aysén'),
    ('Cisnes','Cisnes'),
    ('Guaitecas','Guaitecas'),
    ('Cochrane','Cochrane'),
    ('O\'Higgins','O\'Higgins'),
    ('Tortel','Tortel'),
    ('Chile Chico','Chile Chico'),
    ('Río Ibáñez','Río Ibáñez'),
    ('Punta Arenas','Punta Arenas'),
    ('Laguna Blanca','Laguna Blanca'),
    ('Río Verde','Río Verde'),
    ('San Gregorio','San Gregorio'),
    ('Cabo de Hornos','Cabo de Hornos'),
    ('Antártica','Antártica'),
    ('Porvenir','Porvenir'),
    ('Primavera','Primavera'),
    ('Timaukel','Timaukel'),
    ('Natales','Natales'),
    ('Torres del Paine','Torres del Paine'),
    ('Santiago','Santiago'),
    ('Cerrillos','Cerrillos'),
    ('Cerro Navia','Cerro Navia'),
    ('Conchalí','Conchalí'),
    ('El Bosque','El Bosque'),
    ('Estación Central','Estación Central'),
    ('Huechuraba','Huechuraba'),
    ('Independencia','Independencia'),
    ('La Cisterna','La Cisterna'),
    ('La Florida','La Florida'),
    ('La Granja','La Granja'),
    ('La Pintana','La Pintana'),
    ('La Reina','La Reina'),
    ('Las Condes','Las Condes'),
    ('Lo Barnechea','Lo Barnechea'),
    ('Lo Espejo','Lo Espejo'),
    ('Lo Prado','Lo Prado'),
    ('Macul','Macul'),
    ('Maipú','Maipú'),
    ('Ñuñoa','Ñuñoa'),
    ('Pedro Aguirre Cerda','Pedro Aguirre Cerda'),
    ('Peñalolén','Peñalolén'),
    ('Providencia','Providencia'),
    ('Pudahuel','Pudahuel'),
    ('Quilicura','Quilicura'),
    ('Quinta Normal','Quinta Normal'),
    ('Recoleta','Recoleta'),
    ('Renca','Renca'),
    ('San Joaquín','San Joaquín'),
    ('San Miguel','San Miguel'),
    ('San Ramón','San Ramón'),
    ('Vitacura','Vitacura'),
    ('Puente Alto','Puente Alto'),
    ('Pirque','Pirque'),
    ('San José de Maipo','San José de Maipo'),
    ('Colina','Colina'),
    ('Lampa','Lampa'),
    ('Til Til','Til Til'),
    ('San Bernardo','San Bernardo'),
    ('Buin','Buin'),
    ('Calera de Tango','Calera de Tango'),
    ('Paine','Paine'),
    ('Melipilla','Melipilla'),
    ('Alhué','Alhué'),
    ('Curacaví','Curacaví'),
    ('María Pinto','María Pinto'),
    ('San Pedro','San Pedro'),
    ('Talagante','Talagante'),
    ('El Monte','El Monte'),
    ('Isla de Maipo','Isla de Maipo'),
    ('Padre Hurtado','Padre Hurtado'),
    ('Peñaflor','Peñaflor')
)