# Constantes para el log
ERROR = 4
AUTHENTICATE = 5
VALIDATE = 6
LOGIN = 7
LOGOUT = 8
FORGOT = 9
ADVERTISEMENT = 10
TRANSACTION = 11
BITCOIN_RECEPTION = 12
CRYPTOCURRENCY_SEND = 13
ACCOUNT_BALANCE = 14
