# Generated by Django 2.1.3 on 2019-01-23 23:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import folios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conectores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tiempo y fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Tiempo y fecha de modificación')),
                ('unique_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('caf', models.FileField(blank=True, null=True, upload_to=folios.models.upload_file_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])], verbose_name='CAF')),
                ('rut', models.CharField(max_length=255)),
                ('tipo_de_documento', models.IntegerField()),
                ('rango_desde', models.IntegerField()),
                ('rango_hasta', models.IntegerField()),
                ('folio_actual', models.IntegerField()),
                ('folios_disponibles', models.IntegerField()),
                ('fecha_de_autorizacion', models.DateTimeField()),
                ('fecha_de_vencimiento', models.DateTimeField()),
                ('pk_modulo', models.CharField(max_length=255)),
                ('pk_exponente', models.CharField(max_length=255)),
                ('pem_public', models.TextField(default='', null=True)),
                ('pem_private', models.TextField(default='', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vencido', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conectores.Compania')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
            },
        ),
    ]
